apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-sa
  namespace: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/eksclusterroleaq-eks-node-role


# ---
# # Cluster Role for External-DNS
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cluster-role
#   namespace: external-dns
# rules:
# - apiGroups: [""]
#   resources: ["services"]
#   verbs: ["get", "watch", "list"]
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "watch", "list"]
# - apiGroups: ["networking.k8s.io"]
#   resources: ["ingresses"]
#   verbs: ["get", "watch", "list"]
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["get", "watch", "list"]

# ---
# # Cluster Role Binding
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: cluster-role-binding
#   namespace: external-dns
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-role
# subjects:
# - kind: ServiceAccount
#   name: external-dns-sa
#   namespace: external-dns
