# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: externaldns
#   namespace: external-dns
#   labels:
#     app: externaldns
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: externaldns
#   template:
#     metadata:
#       labels:
#         app: externaldns
#     spec:
#       serviceAccountName: external-dns-sa  
#       containers:
#         - name: nginx
#           image: nginx:latest
#           ports:
#           - containerPort: 80


# --- 
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
#   namespace: external-dns
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: "aqeel.groveops.net"
# spec:
#   # type: LoadBalancer
#   selector:
#     app: externaldns
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
# --- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-ingress
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: aqeel.groveops.net
    kubernetes.io/ingress.class: aws-load-balancer
spec:
  rules:
  - host: "aqeel.groveops.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-dns
            port:
              number: 80
  
  tls:
  - hosts:
    - aqeel.groveops.net 
    secretName: example-com-tls 
