apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  values:
    deployment:
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.13.1
          command:
            - /bin/sh
            - -c
            - |
              /opt/external-dns/external-dns $(EXTERNAL_DNS_ARGS)
          env:
            - name: EXTERNAL_DNS_ARGS
              valueFrom:
                configMapKeyRef:
                  name: external-dns-config
                  key: external-dns-args

    aws:
      region: us-west-1
      credentials:
        external: true 