
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - helm-repository.yaml
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  # - values.yaml



