apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-sa
  namespace: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::489994096722:role/eksclusterroleaq-eks-node-role